### ISSUE TITLE
Create github Jest Test Workflow

### ISSUE THREAD

**Issue by canaleal** [canaleal/Svelte-Portfolio#23]
```
name: Unit Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
  
  ```
